// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gb22OgejyqCyoT7kZ5r5o1ufCFJIbd4',
    appId: '1:1075064472296:web:23762d40497a85ecfaff5d',
    messagingSenderId: '1075064472296',
    projectId: 'sura-app-ee922',
    authDomain: 'sura-app-ee922.firebaseapp.com',
    storageBucket: 'sura-app-ee922.firebasestorage.app',
    measurementId: 'G-68ZXMYRYV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkjZ3QgDBk0pBPSOiPXlnhvY1tQMihNk',
    appId: '1:1075064472296:android:59b4e4664dda93dffaff5d',
    messagingSenderId: '1075064472296',
    projectId: 'sura-app-ee922',
    storageBucket: 'sura-app-ee922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZnC6KTIUM-Ej9D6A6SsTA1cv0PBv2l0g',
    appId: '1:1075064472296:ios:a4ebc67dff270e6ffaff5d',
    messagingSenderId: '1075064472296',
    projectId: 'sura-app-ee922',
    storageBucket: 'sura-app-ee922.firebasestorage.app',
    androidClientId: '1075064472296-2mfl77k7dfkg5ilf9psscmuf48euokgi.apps.googleusercontent.com',
    iosClientId: '1075064472296-bh7pe9bolorkaa298o01c04t0j547v0q.apps.googleusercontent.com',
    iosBundleId: 'com.sura.suraApp',
  );

}